export const photos = {
  hero: "/images/building.avif",
  building: "/images/building.avif",
  campus: "/images/building.avif",
  classroom: "/images/classroom.avif",
  computerLab: "/images/computer-lab.avif",
  earlyYears: "/images/early-years.avif",
  storytellers: "/images/storytellers.avif",
  library: "/images/classroom.avif",
  academics: "/images/classroom.avif",
  sports: "/images/building.avif",
  arts: "/images/storytellers.avif",
  character: "/images/early-years.avif",
  science: "/images/computer-lab.avif",
  farming: "/images/building.avif",
  podcast: "/images/storytellers.avif",
};
export const stages = [
  {
    name: "Early Years",
    range: "Nursery — PP2 · EYFS – UK",
    title: "Play-based. Language-rich.",
    text: "Play, stories, music, and movement that grow language, social confidence, and a love of discovery.",
    subjects: "Play · Language · Social confidence · Stories · Music · Movement",
    image: photos.earlyYears,
  },
  {
    name: "Primary School",
    range: "Grades 1 — 5 · Cambridge Primary",
    title: "Concept-led. Inquiry-driven.",
    text: "Structured, engaging learning with conceptual clarity, problem-solving, classroom mini libraries, AI awareness, robotics, and sport for teamwork.",
    subjects: "Concepts · Inquiry · Mini libraries · AI & robotics · Sport",
    image: photos.classroom,
  },
  {
    name: "Middle School",
    range: "Grades 6 — 7 · Integrated Curriculum",
    title: "Analytical. Application-ready.",
    text: "Independent, reflective learners applying knowledge to real contexts — with digital literacy, communication, leadership, and resilient character.",
    subjects: "Analysis · Real-world use · AI & robotics · Leadership · Resilience",
    image: photos.computerLab,
  },
  {
    name: "Pedagogy",
    range: "Active Learning",
    title: "Student-centred classrooms.",
    text: "Hands-on inquiry, collaboration, discussion, and interdisciplinary links — so learning is experienced, not only heard.",
    subjects: "Inquiry · Collaboration · Experiential · Real-world · Holistic",
    image: photos.storytellers,
  },
  {
    name: "Curriculum",
    range: "Global–Indian · CBSE strengths",
    title: "Designed for today. Ready for tomorrow.",
    text: "UK National Curriculum foundation, Cambridge International, and key CBSE strengths — adapted for Indian context, values, and culture.",
    subjects: "Strong academics · Conceptual clarity · Global exposure · Cultural grounding",
    image: photos.building,
  },
];
