export const photos = {
  hero: "/images/campus-playground.avif",
  building: "/images/campus-playground.avif",
  campus: "/images/campus-playground.avif",
  classroom: "/images/classroom-desks.avif",
  computerLab: "/images/computer-lab-desks.avif",
  earlyYears: "/images/early-years-room.avif",
  storytellers: "/images/value-education-lab.avif",
  library: "/images/classroom.avif",
  academics: "/images/classroom.avif",
  sports: "/images/sports-basketball.avif",
  arts: "/images/storytellers.avif",
  character: "/images/value-education-lab.avif",
  science: "/images/robotics-workstations.avif",
  roboticsLab: "/images/robotics-lab.avif",
  farming: "/images/building.avif",
  podcast: "/images/storytellers.avif",
  biophilic: "/images/biophilic-atrium.avif",
};
export const stages = [
  {
    name: "Early Years",
    range: "Nursery — PP2 · Foundational Stage",
    title: "Play-based. Language-rich.",
    text: "Play, stories, music, and movement that grow language, social confidence, and a love of discovery.",
    subjects: "Play · Language · Social confidence · Stories · Music · Movement",
    image: photos.earlyYears,
  },
  {
    name: "Primary School",
    range: "Grades 1 — 5 · CBSE Primary",
    title: "Concept-led. Inquiry-driven.",
    text: "Structured, engaging learning with conceptual clarity, problem-solving, classroom mini libraries, AI awareness, robotics, and sport for teamwork.",
    subjects: "Concepts · Inquiry · Mini libraries · AI & robotics · Sport",
    image: photos.classroom,
  },
  {
    name: "Middle School",
    range: "Grades 6 — 7 · CBSE Middle",
    title: "Analytical. Application-ready.",
    text: "Independent, reflective learners applying knowledge to real contexts — with digital literacy, communication, leadership, and resilient character.",
    subjects: "Analysis · Real-world use · AI & robotics · Leadership · Resilience",
    image: photos.computerLab,
  },
  {
    name: "Pedagogy",
    range: "Active Learning",
    title: "Student-centred classrooms.",
    text: "Hands-on inquiry, collaboration, discussion, and interdisciplinary links — so learning is experienced, not only heard.",
    subjects: "Inquiry · Collaboration · Experiential · Real-world · Holistic",
    image: photos.storytellers,
  },
  {
    name: "Curriculum",
    range: "CBSE · Holistic Learning",
    title: "Designed for today. Ready for tomorrow.",
    text: "A CBSE curriculum focused on conceptual understanding, not memorisation — with strong academics, values, creativity, and culture.",
    subjects: "Strong academics · Conceptual clarity · Values · Cultural grounding",
    image: photos.building,
  },
];
